name: test
on: 
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@v3
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "TEST!!!!!!"